name: Build Mkdocs Site
on:
  push:
    branches:
      - dev
      - main

jobs:
  docker:
    name: Build Mkdocs site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build local docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: app:latest

      - name: Run mkdocs build via docker
        uses: addnab/docker-run-action@v3
        with:
          image: app:latest
          options: --rm -v ${{ github.workspace }}:/docs
          run: |
            git config --global --add safe.directory /docs
            mkdocs build

      - name: Deploy to site/staging (from dev)
        if: endsWith(github.ref, '/dev')
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "<>"
          sudo chown -R $USER:$USER site
          git fetch origin site/staging
          git switch site/staging
          rm -rf ./*
          cp -r site/* .
          rm -rf site
          git add .
          git commit -m "Deploy dev build to staging"
          git push origin site/staging

      - name: Deploy to site/production (from main)
        if: endsWith(github.ref, '/main')
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "<>"
          sudo chown -R $USER:$USER site
          git fetch origin site/production
          git switch site/production
          rm -rf ./*
          cp -r site/* .
          rm -rf site
          git add .
          git commit -m "Deploy main build to production"
          git push origin site/production
